### ISSUE TITLE
Improve surfaces behavior to not require default content only via "surface-default" element

### ISSUE THREAD

**Issue by remisbaima** [liferay/senna.js#102]
In http://sennajs.com/docs/#dataattributes we see:
```
<div id="content" data-senna-surface>
  <div id="content-default">
    Default content of my website.
  </div>
</div>
```
Document that the sub-div "content-default" **must** have the "-default" suffix and that it **must** be called "-default" and not any other suffix.

**Comment by eduardolundgren** [comment]
Done.
