### ISSUE TITLE
Make Senna available in a CDN

### ISSUE THREAD

**Issue by remisbaima** [liferay/senna.js#103]
Like you provide the http://alloyui.com in a CDN.

**Comment by jimaek** [comment]
Its available on jsDelivr with auto-updates enabled http://www.jsdelivr.com/projects/senna.js

More info https://hacks.mozilla.org/2014/03/jsdelivr-the-advanced-open-source-public-cdn/

**Comment by remisbaima** [comment]
@jimaek: that is great, but it should be documented in the main page http://sennajs.com

**Comment by dimadin** [comment]
Could you please also add it to [cdnjs](https://cdnjs.com/)? It is similar to jsDelivr since it is [open source](https://github.com/cdnjs/cdnjs), even I could open issue there, but I am not sure do you also want to submit CSS and if you want it just when version 1.0 is released.

**Comment by zenorocha** [comment]
Just opened an issue for cdnjs: https://github.com/cdnjs/cdnjs/issues/8163

**Comment by lukehutch** [comment]
The PR for cdnjs never got finished, and the issue was closed due to lack of response:
https://github.com/cdnjs/cdnjs/pull/8173
