### ISSUE TITLE
Error with slug when used in some browsers

### ISSUE THREAD

**Issue by dimadin** [liferay/senna.js#107]
This is happening in some browsers that are not major ones, I suppose some feature that they don't support is used.

When you are using latest build, it works for content but slug changes to `/undefined` for all pages. This is happening in [Pale Moon](http://www.palemoon.org/) (fork of older Firefox with some features removed) and in [Dolphin](http://www.dolphin.com/) and [Next Browser](http://nextbrowser.goforandroid.com/) on Android, for example.

**Comment by eduardolundgren** [comment]
@dimadin This issue is no longer reproducible on 1.0.0-alpha. Thanks!
