### ISSUE TITLE
Fix blog demo

### ISSUE THREAD

**Issue by dimadin** [liferay/senna.js#108]
There is an example for infinity scroll right now, but when ported and used with latest build shows some errors; looks like there were a lot of changes in the meantime.

I use [WordPress](https://wordpress.org/) for site building (other CMSs are similar) and when used in blog format, it adds `/page/<num>` for older archive pages. There are some methods right now that use infinity scrolling but that make POST request and get JSON response (example [here](http://ma.tt/)).

On the other hand, there are some full page cache mechanisms for WordPress which means that page is loaded like static file and that when used in combination with Senna.js could make really fast page loading while at the same time much less resource heavy (example [here](http://blog.milandinic.com/)).

I could even help in making some plugin for WordPress in the future that uses this technique to have a greater reach of Senna.js.

**Comment by zenorocha** [comment]
Just checked the blog demo and it's not working like @dimadin reported.

The issue is related to `senna.debounce` which appears to be removed.

**Comment by zenorocha** [comment]
Fixed at https://github.com/liferay/senna.js/commit/0792063c0941ff8d1e81cc4851a57fcc8368e3b9

Thanks for reporting @dimadin!
