### ISSUE TITLE
Pull requests tests failing due to security restrictions on SauceLabs

### ISSUE THREAD

**Issue by henvic** [liferay/senna.js#110]
Currently pull requests tests are failing due dependency on SauceLabs.

I think we can use one of these two approaches:
1. verify if the SAUCE_USERNAME environmental variable is defined and only run the tests if it is
2. try to be smart and run the locally available Chromium if SAUCE_USERNAME is not defined (as it once worked with 5848eb066096d7a1e9086399c2f5b53212ce590d and removed by 84be2878d181ad76ded5c391292a53467a0d747e + changes on how we use karma).

Please see https://github.com/henvic/senna/commit/57da51a960d84590779dc3e6a4b398accde6fb10 or https://github.com/henvic/senna/tree/fix-pr-saucelabs-travis to see how I tried to make **2** work.

It appears to me the only thing missing right now is disabling the Chromium sandbox as in https://github.com/liferay/senna.js/commit/5848eb066096d7a1e9086399c2f5b53212ce590d#diff-a2a3b7b0c9c3b4b93b4aebf4e3ec3cfbR43 to make it working back.

Anyone has an idea about how to do it without messing too much with the code elsewhere? **2** is nice to have as it gives instant feedback to the community. Otherwise, let's just go with **1** and at least provide partial info.

PS: btw, a fork can set their own secret keys and test it, but it's not as obvious & we shouldn't expect eventual people from the community contributing to do so.

References:
* https://docs.travis-ci.com/user/sauce-connect/
* https://docs.travis-ci.com/user/gui-and-headless-browsers/

**Comment by FagnerMartinsBrack** [comment]
Is this because Sauce tests can't be run in PRs? If so it might be related to https://github.com/carhartl/jquery-cookie/issues/268, there is a very useful discussion there.

**Comment by eduardolundgren** [comment]
Fixed. Thx.
