### ISSUE TITLE
New website

### ISSUE THREAD

**Issue by eduardolundgren** [liferay/senna.js#116]
Version 1.0.0 is almost out with many new features!

In order to accompany the new version a website revamp is mandatory.

We are looking for some help here, **if you are interested in being part of the team and helping Senna project** with your web developer skills let us know :)

**Comment by mateusortiz** [comment]
:+1:

**Comment by luiztiago** [comment]
:+1:

**Comment by zenorocha** [comment]
We have a repository dedicated to the site so we should probably move this discussion there. https://github.com/liferay/sennajs.com
