### ISSUE TITLE
Your use of almost washed-out color Type on your web-site makes text unreadable

### ISSUE THREAD

**Issue by billwoo** [liferay/senna.js#117]
### Expected behaviour

I thought I would read the documentation

### Actual behavior

It's almost illegible.

### Steps to reproduce

1. go look

### Browsers affected

Chrome

**Comment by eduardolundgren** [comment]
Thanks for the feedback! We are planning the new docs and website pages and will be fixed.

**Comment by zenorocha** [comment]
Closing this one since it's related to #116. Thanks for reporting @billwoo!
