### ISSUE TITLE
RequestScreen getRequestPath doesn't work on IE

### ISSUE THREAD

**Issue by jbalsas** [liferay/senna.js#118]
### Expected behaviour

On IE, invoking `RequestScreen::getRequestPath` should return the response url

### Actual behaviour

Instead of the reponse url, it always returns `"/"`

### Browsers affected

This affects IE since `XMLHttpRequest.responseURL` is not supported (see https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseURL)

**Comment by jbalsas** [comment]
Hey @eduardolundgren, I've pushed a possible fix to my branch [here](https://github.com/jbalsas/senna.js/commit/6bc099978dfbdee30ec99702520335a00559e1ea). I can send it as a PR if this is the way we want to go, or we can explore other options...

**Comment by eduardolundgren** [comment]
Good catch! The reason to read from the `xhr` is because the request could have suffered a 302 redirect and which is computed by `xhr.responseURL`. Let me look if there is any way to get this information on IE.

**Comment by eduardolundgren** [comment]
I guess there is not nice fix for this. The solution is to configure the server to set the response HTTP header `X-Request-URL` to the current URL after any redirect that might have happened. It should be safe to set it unconditionally. Let me dig a bit more before conclusion.

**Comment by jbalsas** [comment]
Mmm... yeah, the server approach will be more reliable when the user is in control of it. However, that might not always be the case, so at least replacing the state with the navigated path (even if it doesn't account for redirects) might be better than nothing. From this project point of view, at least :)

**Comment by eduardolundgren** [comment]
Fixed here https://github.com/liferay/senna.js/commit/0cff1e505ce11d685ace3424d3119333d1a876cc.

Thanks!
