### ISSUE TITLE
updateScrollPosition not working

### ISSUE THREAD

**Issue by nedpals** [liferay/senna.js#122]
Hi! I'm very new to Senna.js. What I wanted to do in the page is that the scroll position of the page must not goe back to the top once it updates it navigates to another. I followed the code posted at #55 : 

`app.setUpdateScrollPosition(false);`

I tried it but still it goes back to the top so I used the browser's (I'm using Firefox) JS console and pasted the code to get the result but it shows like this:

`TypeError: app.setUpdateScrollPosition is not a function`

I modified the code to this:

`app.setUpdateScrollPosition = false;`

and still doing the same behavior. Any solutions? Thanks in advance.

**Comment by eduardolundgren** [comment]
The setter exists https://github.com/liferay/senna.js/blob/master/src/app/App.js#L986

I suspect that you are not accessing the right `app` instance. How are you instantiating Senna, via JavaScript or data attributes?

**Comment by nedpals** [comment]
I instantiating Senna using both methods. I think I should ditch the Javascript one since I initialized using data-attributes. Is there anything that I should do in order for it to work by using the data-attributes?

**Comment by eduardolundgren** [comment]
To access the app initialized by the data attribute you should use:

```js
var app = senna.dataAttributeHandler.getApp();
app.setUpdateScrollPosition(false);
```

**Comment by nedpals** [comment]
It's working thanks.
