### ISSUE TITLE
IE11 does not apply temporary annotated style sheets after navigation

### ISSUE THREAD

**Issue by mjbradford89** [liferay/senna.js#124]
I'm not 100% sure this is a bug in Senna or Liferay, but the related issue is this one: https://issues.liferay.com/browse/LPS-64816.

Navigating from a page with a `data-senna-track="temporary"` annotated css file, to a page with the same css file, removes the link to this file, and then it gets re-appended on the next screen.  Doing this apparently causes an issue in IE11 where styles from this file in media queries are not applied until there is a page redraw.

##### Steps to reproduce (in liferay)

1. see https://issues.liferay.com/browse/LPS-64816.
2. After following the steps, you can see the media queries are not applied, but then resizing the browser will cause them to be applied.

##### Steps to reproduce (outside of liferay)

1. In `senna.js/examples/basic/index.html` replace the content with the following:

```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Basic</title>
  <link rel="shortcut icon" href="http://sennajs.com/images/favicon.ico">

  <!-- Including Senna -->
  <script src="../../build/globals/senna-debug.js"></script>

  <link data-senna-track="temporary" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
</head>
<body id="body">
  <h1>index.html</h1>
  <div>
      <a href="index.html">Click me to navigate</a>
  </div>
  <div class="row">
    <div style="background-color: blue;" class="col-md-6">col-md-6</div>
    <div style="background-color: red;" class="col-md-2">col-md-2</div>
    <div style="background-color: orange;" class="col-md-4">col-md-4</div>
  </div>

  <script>
    'use strict';
    var app = new senna.App();
    app.setBasePath('/examples/basic');
    app.addSurfaces(['body']);
    app.addRoutes([
      {
        path: '/index.html',
        handler: senna.HtmlScreen
      }
    ]);
  </script>
</body>
</html>
```

2. run gulp server
3. Navigate to the page in IE11, notice bootstrap column layout is applied.
4. Click the link
5. Notice the styles are not applied, and then are applied if the browser is resized.

##### Browsers affected

IE11

##### Potential solution

It seems like one way to prevent this issue is to not remove `temporary` resources when the next surface requires that same resource.  If you think this is a good solution I can try and implement it.

**Comment by mjbradford89** [comment]
I was able to come up with a test case outside of liferay that demonstrates the issue.  I updated the description and attached a gif.

![ie-issue](https://cloud.githubusercontent.com/assets/6517855/14446812/e3bb6b36-000e-11e6-9617-8c2e0dfd7db2.gif)

**Comment by eduardolundgren** [comment]
@brunobasto Do you have time to look this issue? I won't be able to look in any time soon.
Thanks @mjbradford89.

**Comment by brunobasto** [comment]
Hey @eduardolundgren,

I'll talk to @mjbradford89.

**Comment by mjbradford89** [comment]
Hey guys, I found out some more info on the problem.  It seems like it's more to do with IE caching than an actual issue in senna.

The bug happens when IE, after a resource has been removed/reappended, resolves the request for css from cache without re-validation, `200 (from cache)`.  Then IE does not try and reapply these styles.

But if the request resolves as just `200`, or `304 / Not Modified`, the styles are then applied correctly.

In Portal, I was able to fix the problem by changing the cache control header to be `must-revalidate, max-age=-1, public`.  But I'm not sure if that is a valid fix.

**Comment by eduardolundgren** [comment]
Another possible solution is before appending the `newStyle` inside `HtmlScreen` check for `href` and if present mutate it an unique url using https://github.com/metal/metal-uri/blob/master/src/Uri.js#L246.

**Comment by eduardolundgren** [comment]
Similar to what we do here https://github.com/liferay/senna.js/blob/master/src/screen/RequestScreen.js#L114-L116

**Comment by mjbradford89** [comment]
Oh I like that solution better :smiley:.  Would it be a problem that this would cause CSS to never really be cached in IE?  We could just target <= IE11, since Edge does not have this problem.

I'll implement it and test it out.

**Comment by mjbradford89** [comment]
Submitted a pull: https://github.com/liferay/senna.js/pull/125

**Comment by eduardolundgren** [comment]
Merged, thank you! :)
Tagged new version also https://github.com/liferay/senna.js/releases/tag/v1.0.2
