### ISSUE TITLE
IE11/Edge form submit - 302 redirect to same page will serve cached content

### ISSUE THREAD

**Issue by mjbradford89** [liferay/senna.js#126]
This issue causes https://issues.liferay.com/browse/LPS-63690 in portal.

### Expected behaviour

Submitting a form that responds with a redirect (302 or other), will fetch the content from the server instead of browser cache.  This is especially crucial when logging in with the expectation of ending up on the same url, like in LPS-63690.

### Actual behaviour

The browser will submit the form, server responds with 302 `Location: htttp://www.localhost.com` header, and if the login was originally sent from that same page, no navigation will happen, because it is served from browser cache. 

### Steps to reproduce

1. go to `senna.js/examples/form/`
2. Change `server.js` to 
```

var express = require('express');
var multer = require('multer')
var app = express();
var upload = multer();

app.get('/examples/form/*', function(req, res, next) {
	res.setHeader('Cache-Control', 'null');
	next();
});

// Serve files
app.use(express.static('../../'));

app.post('/post', upload.array(), function(req, res, next) {
	var content = '<div id="result1">';
	content += JSON.stringify(req.body, 5);
	content += '</div>';
	res.end(content);
});

app.post('/post-get', upload.array(), function(req, res, next) {
	res.redirect('/examples/form/index.html');
});

// Server
app.listen(3000);
```

3. run `node server.js`
4. navigate to `localhost:3000/examples/form/index.html`
5. Open dev-tools and go to the Network tab
6. Submit the Post Redirect Get form
7. Notice in the network panel that the second request to `index.html` is status 200 (**from cache**).

### Browsers affected

IE11/Edge

**Comment by mjbradford89** [comment]
I believe I have a fix for this one.  Just writing a unit test now and will submit to @brunobasto.

**Comment by brunobasto** [comment]
Awesome! Thanks @mjbradford89.

**Comment by mjbradford89** [comment]
sent a pull: https://github.com/brunobasto/senna.js/pull/1

**Comment by jbalsas** [comment]
Awesome analysis, @mjbradford89! Great job!

**Comment by mjbradford89** [comment]
Closing this issue as it was resolved by https://github.com/liferay/senna.js/pull/129
