### ISSUE TITLE
Image fails to show up when using senna with main route file that is not on the url's root

### ISSUE THREAD

**Issue by mairatma** [liferay/senna.js#131]
### Expected behaviour

Image should show up.

### Actual behaviour

Image doesn't show up. The GET request fails, and inspecting the network request shows that the url that was fetched is wrong. See screenshots:
<img width="640" alt="screen shot 2016-05-06 at 1 17 38 pm" src="https://cloud.githubusercontent.com/assets/5216049/15079101/edf54086-138c-11e6-866c-c8e6dfd36282.png">

<img width="669" alt="screen shot 2016-05-06 at 1 07 38 pm" src="https://cloud.githubusercontent.com/assets/5216049/15079106/f17d18e6-138c-11e6-95b5-3809082c0ac3.png">

### Steps to reproduce

I've created a repo that reproduces this problem [here](https://github.com/mairatma/senna-img-bug). But I'll try to list the steps anyway.

1. Create a project that has an **index.html** file inside some folders (I used **demos/senna/index.html**).
2. Prepare it to use senna, having an image as the content of the main file, like [this](https://github.com/mairatma/senna-img-bug/blob/master/demos/senna/index.html).
3. Run a server on the project's root directory.
4. Open **index.html**

### Browsers affected

Tested in both Chrome and Firefox, happens in both.

### Note

I've tried investigating what happened, but can't find out what's going on.

One thing that I've noticed is that it only happens if **index.html** is not at the root of the main url. I've also added this on the repo I've mentioned. If you open the **index.html** at the root all works fine, but not with the one inside **demos/senna**.

Another thing I've just noticed is that it stops happening if instead of `'/demos/senna'` I use `'/demos/senna/'`. So probably something related to urls not ending in `/`. Though I don't get this on other urls I've used like this.

**Comment by mairatma** [comment]
Forget the last thing I said, about setting the route to `/demos/senna/` fixing the problem. I thought it was fixed because senna wasn't detecting the route correctly with that url, which is a separate bug (already sent a [pr](https://github.com/liferay/senna.js/pull/132) for this).

So the only thing that I know works is to have the **index.html** file in the project root.

**Comment by mjbradford89** [comment]
I think this is happening because we are using `window.history.pushState`, and changing the relative path of the current document.  So instead of `/demos/senna/`, it's now `/demos/senna`,  so the relative path on the image, `img/img1.jpg`, interprets that as `http://localhost:8000/demos/img/img1.jpg` instead of the correct path `http://localhost:8000/demos/senna/img/img1.jpg`.  Notice the missing `/senna/`.

But even knowing this, I'm not sure what the right change is to fix this.  I think not removing that trailing `/` on the relative path would work this time, but would break navigation in other situations.

**Comment by eduardolundgren** [comment]
We have a related issue open here https://github.com/metal/metal-uri/issues/3. We need to analyze what is the proper behavior for those different scenarios.

**Comment by mairatma** [comment]
Eduardo helped me out with this, it seems like it's not really a bug at all, this is the expected browser behavior, it's trying to fetch the image by using its relative path with different urls each time. This can be fixed by adding a `<base href="/demos/senna/">` tag to `head`.

It's not a bug then, so I'm closing this. It might be cool to try to have senna make this easier for developers, so they don't have to worry about `base` themselves, but not sure how we could achieve this.
