### ISSUE TITLE
Canceled history navigation can remove styles prematurely

### ISSUE THREAD

**Issue by mjbradford89** [liferay/senna.js#136]
This issue causes https://issues.liferay.com/browse/LPS-66049 in portal.
### Expected behaviour

Clicking back button twice consecutively will not cause any flash of unstlyed content.
### Actual behaviour

Clicking back button twice can can cause a flash of unstlyed content.

![2016-05-23_16-48-12](https://cloud.githubusercontent.com/assets/6517855/15624234/00b5c69a-2437-11e6-900c-327dde297d04.gif)
### Steps to reproduce

It can be difficult to reproduce, but I've seen it happen a couple times after a lot of testing.
1. Navigate to several pages.
2. Click the browser back button.
3. As soon as navigation starts, click the back button again.
### Browsers affected

All major browsers seem to be affected.

**Comment by mjbradford89** [comment]
submitted a potential fix to bruno: https://github.com/brunobasto/senna.js/pull/2

**Comment by zenorocha** [comment]
> Closing this issue since a PR is on review at #138

**Comment by jbalsas** [comment]
This apparently got closed... at least we merged code. Although there's likely still similar issues, closing for now and will address in the context of new reports if they come.
