### ISSUE TITLE
Should there be an event for fragment urls (to same page)?

### ISSUE THREAD

**Issue by rotty3000** [liferay/senna.js#140]
### Feature Request

Currently fragment urls to the same page are ignored by the router. However, would it perhaps be appropriate for there to be a special event, rather than ignoring, such that this behaviour could be implemented without any external logic?

For example, given the following event handler:

``` javascript
    var app = senna.dataAttributeHandler.getApp();

    app.on('endNavigate', function(event) {
        // do something
    });
```

it can be observed that fragment urls to the same page do not result in an `endNavigate` event, which after consideration, seems reasonable. 

However, could it make sense to trigger an event something like `endFragmentNavigate` thereby allowing the developer to recognize both scenarios?

**Comment by eduardolundgren** [comment]
Like explained here https://github.com/liferay/senna.js/issues/139#issuecomment-224338818, fragments works with routes, although they are just delegated to the browser to behave as natively. Therefore no events are fired.

Since it's processed by the router navigation, I agree with you that make sense to fire events for fragments also. Let me look if it won't cause any issues with the existing lifecycle, if not, I think we are safe in adding it. Thanks!

**Comment by eduardolundgren** [comment]
In addition to the event, I found a bug when navigating to different pages with #hash, https://github.com/liferay/senna.js/issues/141.

**Comment by mjbradford89** [comment]
I looked into this one a little and see an easy way to emit a `fragmentNavigate` or `startFragmentNavigate` event.  But I'm not sure if it's possible for an `endFragmentNavigate`, since the browser is handling that natively, and it would be hard to tell when that is complete.  Any ideas?

**Comment by mjbradford89** [comment]
something like this could work for just a general `fragmentNavigate` event: https://github.com/liferay/senna.js/commit/87acb0798f81b64dc28b2999a8e4444a619f14cd

**Comment by rotty3000** [comment]
Is it relevant to determine end of fragment navigation?

I think it's still useful to know that a route was indeed matched for the
url, but simply that what it discovered was a fragment url to the same page
rather than to another page, and that this is delegated to native browser
behavior.

So, I find your last `fragmentNavigate` the most appropriate!

On Thu, Jun 9, 2016 at 4:20 PM, Michael Bradford <notifications@github.com>
wrote:

> something like this could work for just a general fragmentNavigate event:
> 87acb07
> <https://github.com/liferay/senna.js/commit/87acb0798f81b64dc28b2999a8e4444a619f14cd>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/liferay/senna.js/issues/140#issuecomment-225014198>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAI9TNsNWSlo7I-GT9PDl5CJnrblbaXtks5qKHWSgaJpZM4IwFXk>
> .
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by mjbradford89** [comment]
Hey @rotty3000,  Eduardo and I were trying to figure out the best scenario for a fragmentNavigate event to be fired but we were unclear on how exactly it will be used.  Should the path with the hash need to be a registered route for the event to fire?  Or should it fire on any navigation to an element on the page?

It might help to know the scenario you were wanting to listen to this event for.  :smile:

**Comment by rotty3000** [comment]
Imagine you have a `overflow: scroll` block which is the senna target area.

On the page there are urls which are mixed between regular urls which
change the content of the target area and also fragments into existing
content within block.

It may be desirable to update the scroll position of the content in the
block.

Make sense?

**Comment by mjbradford89** [comment]
Yeah that makes sense @rotty3000 .  There is a native browser event, [hashChange](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onhashchange), that you might be able to leverage for that purpose.  But it makes sense that senna should allow you listen for that type of navigation as well.

in your example, the fragment links wouldn't be registered as their own specific routes, correct?

**Comment by rotty3000** [comment]
If I just route everything ".*" Then it should include the fragments. In
fact the regex shouldn't exclude the fragments unless configured to do so.

- Ray
On Jun 29, 2016 10:45 PM, "Michael Bradford" <notifications@github.com>
wrote:

Yeah that makes sense @rotty3000 <https://github.com/rotty3000> . There is
a native browser event, hashChange
<https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onhashchange>,
that you might be able to leverage for that purpose. But it makes sense
that senna should allow you listen for that type of navigation as well.

in your example, the fragment links wouldn't be registered as their own
specific routes, correct?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/liferay/senna.js/issues/140#issuecomment-229482810>,
or mute
the thread
<https://github.com/notifications/unsubscribe/AAI9TNwtcTZml0Wgh4ztwaFNCkC-vMNDks5qQtlJgaJpZM4IwFXk>
.

**Comment by mjbradford89** [comment]
hmm true,  I think currently setting ".*" as a route won't include fragments.  We may want to create a separate issue for that.

**Comment by rotty3000** [comment]
that's not entirely true!

The only reason the route does not process the url with a fragment is because of this block:

https://github.com/liferay/senna.js/blob/master/src/app/App.js#L415-L418

**Comment by mjbradford89** [comment]
After working on a few ways to implement and use a `fragmentNavigate` event,  I'm not sure there is anything senna can provide that the native `hashchange` event does not provide already.   The `overflow: scroll` example could be solved with a `hashchange` listener as easy as an event from Senna.js.

So I would vote to not introduce any new events, and instead recommend users use the native browser behavior for fragment navigation., unless you guys have any other use cases I've missed?

**Comment by rotty3000** [comment]
it's just ugly to also have to use `hashchange` because senna already did all the work up to that point! that seems like wasted processing time.

but it's not a showstop I guess

**Comment by jbalsas** [comment]
Dropping this one too as I go through some cleanup.. .sorry Ray! 😢 

Please, reach out if this is still relevant somehow so we can analyze it and re-prioritize it accordingly!
