### ISSUE TITLE
Issue that fragment is lost when navigating to different page with fragment (#hash)

### ISSUE THREAD

**Issue by eduardolundgren** [liferay/senna.js#141]
### Expected behaviour

Navigation from `a.html -> a.html#hash` or `a.html -> b.html#hash` should keep the `#hash` fragment on the browser url.
### Actual behaviour

Currently it's loosing the #hash when navigating to different pages.
### Steps to reproduce

![](http://f.cl.ly/items/2F2k3p1t2G040q3r3y45/fragment-bug.gif)

Download example: http://cl.ly/0P082r0i201c/fragment.zip
### Browsers affected

All.

**Comment by mjbradford89** [comment]
Sure, looking into this today.

**Comment by mjbradford89** [comment]
Sent an update to Bruno for review: https://github.com/brunobasto/senna.js/pull/3

**Comment by brunobasto** [comment]
This issue is fixed by https://github.com/liferay/senna.js/pull/201
