### ISSUE TITLE
Server calls when using "back" button

### ISSUE THREAD

**Issue by wayward710** [liferay/senna.js#147]
When I click the "back" button, there are server requests (that show up in the Navigation view of the web console).

For example, if I'm on "http://mysite.com/web?page1" and then navigate to "http://mysite.com/web?page2" using Senna routes, and then click the "Back" button, I see a request that looks like "http://mysite.com/web?page1" (with a status of 200) in the network view. 

Is there any way to turn off these requests?  It doesn't make them on forward navigation because the defaultEnabled property on the triggering event is false.

**Comment by eduardolundgren** [comment]
This is happening because you didn't call `app.dispatch()` on the page load for the main page. This allows Senna to prefetch the content a head of time.

**Comment by brunobasto** [comment]
@eduardolundgren Should we have an option to auto dispatch on the constructor or something?

**Comment by jbalsas** [comment]
Discarding as we triage old issues that never got enough traction for us to work on them.
