### ISSUE TITLE
Follow 301 redirects

### ISSUE THREAD

**Issue by zenorocha** [liferay/senna.js#151]
If you have a link that redirects to another one using a 301 redirect, Senna should be able to follow it instead of throwing an error.

**Comment by brunobasto** [comment]
Hey @zenorocha,

Can you provide an example? Redirects are already supported.

**Comment by fernandosouza** [comment]
Any news for this Issue? @zenorocha @brunobasto.

**Comment by zenorocha** [comment]
One way to reproduce this problem is by having a link that points to another page and on that page you have a redirect:

`a.html`

```html
<a href="http://example.com/b.html">
```

`b.html`

```html
<meta http-equiv="refresh" content="0; url=http://example.com/c.html" />
```

Senna should be able to know that `b.html` was actually a redirect and then load `c.html`.

**Comment by brunobasto** [comment]
Got it. Thanks, @zenorocha.
