### ISSUE TITLE
Senna not working on HTTPS pages

### ISSUE THREAD

**Issue by zenorocha** [liferay/senna.js#152]
When a user visits a page served over HTTPS and clicks on a link, Senna makes a request to HTTP instead of HTTPS causing a mixed content error.

I had to override the `formatLoadPath` function in order to fix that.

```js
senna.RequestScreen.prototype.formatLoadPath = function(path) {
  var uri = new senna.Uri(path);

  uri.setHostname(window.location.hostname);
  uri.setProtocol(window.location.protocol);

  if (senna.UA.isIeOrEdge && this.httpMethod === senna.RequestScreen.GET) {
    return uri.makeUnique().toString();
  }

  return uri.toString();
};
```

https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content

**Comment by eduardolundgren** [comment]
Since we can only navigate to paths inside the same domain/protocol the fix suggested is appropriate.
We need to just make sure other base parts of the URL is set, such as port (if present).

@mjbradford89 Could you tackle this one too?

Thanks!

**Comment by mjbradford89** [comment]
sure :smile:

**Comment by mjbradford89** [comment]
Submitted the suggested fix: https://github.com/liferay/senna.js/pull/157

**Comment by eduardolundgren** [comment]
Merged. Thanks!
