### ISSUE TITLE
Trackable resources aren't removing js files

### ISSUE THREAD

**Issue by NathanGrimaud** [liferay/senna.js#153]
I'm trying to use trackable ressources for my Cordova app, but it looks that my js files aren't removed after navigation.
It's working for stylesheets.

`<head>`
`<script type="text/javascript"  data-senna-track="temporary" src="./foo.js"></script>`
`<link  data-senna-track="temporary" rel="stylesheet" href="./foo.css" title="index" type="text/css" media="screen" charset="utf-8">`
`</head>`

Routing is done through data attributes.
I can give you more infos if you want :)

**Comment by brunobasto** [comment]
Hey @NathanGrimaud thanks for reporting this.

So, just to clarify:

- you are in "page A" which has foo.js in it's header
- you navigate to "page B" which doesn't have foo.js in it's header
- you can still see the foo.js script tag in there at this point?

Is that it?

Does the code inside foo.js execute once or more than once?

**Comment by NathanGrimaud** [comment]
I'm in "Page A" , foo.js is included in header
Then i navigate to "Page B" which does not contains foo.js, but it's still loaded.
When I go back to "Page A", the parser tells me that it can't redeclare functions inside "foo.js".

foo.js contains a Knockout.js ViewModel, so it's exectuted more than once :)

**Comment by brunobasto** [comment]
Oh, I see. So your problem is that this resource is "permanent" rather than "temporary".

Temporary scripts are executed whenever you navigate to the page containing them. Permanent ones, on the other hand, will only execute once. That's probably what you are looking for.

**Comment by NathanGrimaud** [comment]
Thanks, this now works as i want :)

A last question, is there a way to get a callback when navigation is done with Data attributes ? Maybe a custom Screen ?

**Comment by zenorocha** [comment]
Yes, you can do that:

```js
var app = senna.dataAttributeHandler.getApp();

app.on('endNavigate', function(event) {
    // do something
});
```
