### ISSUE TITLE
Cannot dispatch navigate for urls with fragments

### ISSUE THREAD

**Issue by eduardolundgren** [liferay/senna.js#167]
### Expected behaviour

If a url contains a fragment and there is a router that matches the path it should dispatch navigate.
### Actual behaviour

It will not dispatch navigate for existing route pattern, see https://github.com/liferay/senna.js/blob/master/src/app/App.js#L429.
### Steps to reproduce
1. Create a test.html with route for /foo/*
2. Initialize senna, and call app.dispatch()
3. Open test.html#hash
4. Nothing will be dispatched.

**Comment by brunobasto** [comment]
This issue is fixed by https://github.com/liferay/senna.js/pull/201

See unit test: https://github.com/brunobasto/senna.js/commit/06b33f147263e9bd227df0005ec1a035d9398e57#diff-22806533eb3bde8ad90863fe015e211dR106

**Comment by jbalsas** [comment]
I'm closing this based on the comments on #201. @brunobasto, can you please double check?
