### ISSUE TITLE
Regular expression not matched for manually created routes

### ISSUE THREAD

**Issue by krisak** [liferay/senna.js#168]
When i do the simplest example from the docs:
![screen shot 2016-08-23 at 17 18 39](https://cloud.githubusercontent.com/assets/4954323/17897787/c166e5e6-6955-11e6-88af-a6f5d456e18b.png)

I have no idea how can i be getting there is no route for /random because there obviously is.

**Comment by krisak** [comment]
I am sorry if i am spamming this but i must be superdump or something. 

Thank you.

**Comment by krisak** [comment]
Works as expected when initiated using data attributes.
Data atributes with
`<link rel="senna-route" href="regex:.*" type="senna.HtmlScreen" />`
and 
`var app = {};

document.addEventListener('DOMContentLoaded', function() {
  console.log('domloaded');
   app = senna.dataAttributeHandler.getApp();
});
`
then console says 
`Senna scanned route /.*/
app.navigate('/random');
Navigate to [/random]`

I have no idea why is that happening. Thank you.

**Comment by mjbradford89** [comment]
Hey @krisak, thank you for reporting this.  I was able to reproduce this in our basic example.  I edited the issue title to be more clear.

**Comment by mjbradford89** [comment]
Hey @krisak, after looking into this a bit further, there's actually an issue with your example.  You shouldn't pass in a regular expression as a string.  Instead add your regex route without quotes, like this:

```javascript
    app.addRoutes([
      {
        path: /.*/,
        handler: senna.HtmlScreen
      }
    ])
```

I've tested and confirmed this works.  I'm closing this issue but please reopen it if you're still having issues.

**Comment by krisak** [comment]
I KNEW SOMETHING SUPEROBVIOUS MUST BE GOING ON. THX
