### ISSUE TITLE
More advanced example

### ISSUE THREAD

**Issue by krisak** [liferay/senna.js#169]
I know this is not support forum but i read through all the tickets and try to wrap my head around a source code. But i am asking for good wa to to this.

My issue starts to happen when i want to have some surfaces to not update on certain routes. 
example similar to http://sennajs.com/examples/email/index.html but with little more functionality:
![thearticlesproblem](https://cloud.githubusercontent.com/assets/4954323/17968173/9c3b5b04-6acb-11e6-919c-4f7921e84724.png)

Its a limitation of html to keep contexts of some parts while updating others. But in my example when i try to pick one article that article requested html would have to have context of category selected for it to work. Same goes when i switch category - in html it would probably have the article part empty.

I could just turn off senna for the Article part and ajaxload it directly but i would like to use the history and cashing that senna provides and i am not sure how would i hook into that (cashing especialy).

So i am guessing the custom screen is for that. But how do i affect only one surface? There sadly isnt any custom screen examply.
**Basicaly just need to update some surfaces on certain routes and differend one on others - or disable some surfaces on certain routes.**  
More broadly what would be good aproach here?

Thank you!

Btw love the project.. it solves the classical web problems in elegant easy way. Great thing for presentational websites. And its maintained.

**Comment by mjbradford89** [comment]
Hey @krisak,

Good question.

I think the best/most efficient approach for this is for the server to only send the surface that needs to be updated.  For example:

index.html
```html
<html>
<head>
  <script src="../../build/globals/senna-debug.js"></script>
</head>
<body data-senna>
  <div id="col1" class="col" data-senna-surface>
    Column 1 in index.html
    <a href="col1.html">navigate</a>
  </div>
  <div id="col2" class="col" data-senna-surface>
    Column 2 in index.html
    <a href="col2.html">navigate</a>
  </div>
  <div id="col3" class="col" data-senna-surface>
    Column 3 in index.html
    <a href="col3.html">navigate</a>
  </div>
</body>
</html>
```

col1.html
```html
<html>
<head>
  <script src="../../build/globals/senna-debug.js"></script>
  </head>
  <body data-senna>
    <div id="col1" class="col" data-senna-surface>
      Column 1 updated.

      <a href="index.html">index.html</a>
    </div>
</body>
</html>
```

And then you would have other pages like col2.html, etc..  This minimizes the amount of data in each request.  There are some special cases that would need to be handled server side, like a user navigating directly to url that only returns a surface.  But that should be easy enough to handle with a redirect.

I'm going to close this issue for now.  But feel free to post any other questions.

**Comment by krisak** [comment]
I tried this approach before but it gives me default surface (surface from first visit). It adds -default after the init id.

**Comment by eduardolundgren** [comment]
@krisak I have recorded the issue. Could you confirm if it's the problem you have?

![static](https://cloud.githubusercontent.com/assets/113087/18012127/fd019af6-6b6c-11e6-894a-fa958139292e.gif)

1) Page first loads on index.html - have the surface [index].
2) Then navigate to foo.html -- have the surface [foo].
3) Then navigate to bar.html - that doesn't have the surface.
4) The result is displaying [index] instead of [foo].

If you want to play with it I've also pushed this example here https://github.com/liferay/senna.js/tree/master/examples/static_surface.

It's the expected behavior from the current architecture. During a navigation if the surface content is not found it uses the default content (from the first page load), see https://github.com/liferay/senna.js/blob/master/src/surface/Surface.js#L80. It's how surfaces was designed by default.

It is possible to work-around the problem by a custom Surface class that changes the behavior of the mentioned method. Then when you `addSurfaces` you pass this reference instead.

It's also possible to add something to the library to handle that behavior, like disabling certain surfaces dynamically.

**Comment by krisak** [comment]
Wow thanks guys. You are pretty awesome maintainers. I tried custom surface and well i got somewhere but then decided that its actualy better to use more classic approach. I think this is not feature one would expect and if i did i should probably use some solution that renders everything on client. Since this breaks linkability of website it is sort of antipattern i guess.

On that note Custom Screens example from here http://sennajs.com/docs#screens is pretty missleading. It uses babel helper thats probably not in a scope when you jsut run it in browser with build version. Something like this https://github.com/liferay/senna.js/blob/master/examples/gallery/js/dynamic.js#L27 would be better for newcomers i guess. 

I am obviously not js pro but i guess these are people you get when you do library like that. Maybe i could somehow help with docs or make newcomer tutorial (since i am one). Lot of the github issues seem to be around pretty basic stuff (like how to do transitions etc.).

**Comment by brunobasto** [comment]
@krisak I'm glad you figured out a solution! 

I agree with you that we shouldn't rely on babel helpers in our examples. It would be really appreciated if you were willing to contribute to improve our docs. Feel free to send suggestions and pull request any time: https://github.com/liferay/sennajs.com

Thanks,

**Comment by eduardolundgren** [comment]
@krisak Yeah, this docs are from the times before ES15, we need to update them.

/cc @mjbradford89

**Comment by brunobasto** [comment]
Not using babel helper on the docs anymore: https://github.com/liferay/sennajs.com/commit/5e4cc86288ae2b1f8971e24709cfbcd0b8cf959e

Thx
