### ISSUE TITLE
When senna ready event

### ISSUE THREAD

**Issue by krisak** [liferay/senna.js#171]
Sorry for posting another issue.

Is there any event emitted when senna router kicks in? I am bit worried about the time between "some html shows up" and senna router ready to handle requests. I would just disable site before senna is ready (most of the time i am waiting for fonts anyway).

I cant find anything in the docs or examples. It would be good starting point for bootstraping aplication.

**Comment by eduardolundgren** [comment]
It binds during `DOMContentLoad`, see https://github.com/liferay/senna.js/blob/master/src/app/dataAttributeHandler.js#L12.

If you desire to do something that happens after senna is bound you can do by adding a listener after senna resource is loaded.

```html
<script src=".../senna.js">
<script>
document.addEventListener('DOMContentLoaded', function() {
   /// Runs after senna
});
</script>
```

**Comment by krisak** [comment]
Lovely. Thx. It worked i just was not sure. Another piece for docs i guess.

**Comment by eduardolundgren** [comment]
True. /cc @mjbradford89 One more doc for us to add. Thanks!

**Comment by krisak** [comment]
I will help with the docs when i wrap my head around it.
