### ISSUE TITLE
Track url changes

### ISSUE THREAD

**Issue by b0jan** [liferay/senna.js#173]
In case I have to execute a chunk of JS code on every page change, how do that?

I have setup the app in this way and works fine, the problem is the other scripts are execute only first load of the page.

var app = new senna.App();
app.addSurfaces('main');
app.addRoutes(new senna.Route(/.*/, senna.HtmlScreen));

**Comment by eduardolundgren** [comment]
Have you looked the trackable resources example? https://github.com/liferay/senna.js/tree/master/examples/trackable_resources

This should be enough for what you need.

**Comment by b0jan** [comment]
Yes I'm already using trackable resources. But how can I programmatically track URL changes?
Say in this example:

 for every page change to show in console.log("changed");

**Comment by b0jan** [comment]
Yes I'm already using trackable resources. But how can I programmatically track URL changes?
Say in this example:

var app = new senna.App();
app.addSurfaces('main');
app.addRoutes(new senna.Route(/.*/, senna.HtmlScreen));

for every page change to show in console "Changed"?

**Comment by brunobasto** [comment]
You can try

`app.after('endNavigate', function() {
    console.log('Navigated');
})`

**Comment by eduardolundgren** [comment]
Yep, more info here http://sennajs.com/docs#lifecycleevents

**Comment by b0jan** [comment]
@brunobasto @eduardolundgren Perfect! Thanks guys!

**Comment by eduardolundgren** [comment]
If you are initializing senna from the data attributes and have no access to the `app` instance you can get from `var app = senna.dataAttributeHandler.getApp();`.
