### ISSUE TITLE
Meta tags

### ISSUE THREAD

**Issue by krisak** [liferay/senna.js#191]
Senna automaticaly switches 
```
<title></title>
```
but what about other meta tags like description and stuff like twitter cards etc? 

I guess meta tags are for the crawlers which make single requests thats why its not needed right? Even if crawlers run js (google tries) they don't click they just make single request. So everything should be fine?

**Comment by brunobasto** [comment]
You could go different ways about this if you want to update more things other than just the title. You can add your logic on 

```
app.after('endNavigate', () => {
    updateMetaAndDescription();
});
```

or you could create your own Screen that extends from HtmlScreen:

```
class MyScreen extends HtmlScreen {
    flip(surfaces) {
	return super.flip(surfaces).then(() => {
		updateMetaAndDescription();
	});
    }
}
```

and route your paths through this screen: `app.addRoute(/.*/, MyScreen);`

**Comment by fernandosouza** [comment]
Good point, @krisak. But I think that for the cases you mentioned Senna's behaviour isn't a problem. While a user navigates a site with Senna, and it wants to share that page, crawlers will request the needed information from the original page, not from that one asynchronously loaded from Senna. So, the right meta tags, if they were configured right, will be there.

**Comment by krisak** [comment]
So maybe the question is - is there something in meta tags thats important for browser to be changed? Title sure, maybe some wierder stuff for accesibility? Or edge case like switching languages (that could mess up the encoding)?

If anyone has ideas about that please put them there i will investigate :))

Thx

**Comment by fernandosouza** [comment]
For now, I can say the `dir` attribute of the `<html>` tag. If your project changes the language of the page content using Senna requests.

https://www.w3.org/International/questions/qa-html-dir

**Comment by jbalsas** [comment]
Hey @fernandosouza, attributes in the `<html>` tag are already properly handled. See
- https://github.com/liferay/senna.js/blob/master/src/screen/HtmlScreen.js#L53
- https://github.com/liferay/senna.js/blob/master/test/screen/HtmlScreen.js#L69-L76

**Comment by fernandosouza** [comment]
Awesome, @jbalsas. :)

**Comment by brunobasto** [comment]
Hey @krisak, were you able to come up with some meta tag that should be handled by senna? I think meta tags often depend on the application, so it would be up to the application to handle those - and that could be done using the strategies in https://github.com/liferay/senna.js/issues/191#issuecomment-272206866.

**Comment by krisak** [comment]
I think it should be fine as it is. I was just curious.

**Comment by brunobasto** [comment]
Cool! Thx
