### ISSUE TITLE
document.write is not allowed in content

### ISSUE THREAD

**Issue by jbalsas** [liferay/senna.js#192]
### Expected behaviour

Navigating to a page that includes something with `document.write` in it should work

### Actual behaviour

Depending on how the `document.write` portion is added, two things may happen:
- Inline scripts: whole content will be replaced by the `document.write` content
- External scripts: `Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.` would show on the console

### Steps to reproduce

1. Go to the email example in this repository
2. Edit the `coelho.html` page and add the following
```
 <div class="email-content-body">
    <script>document.write('<h1>foo</h1>');</script>
    …
```
3. Open the example from the `index.html`
4. Click on the `coelho` email
5. The page only shows the `<h1>foo</h1>` tag
6. Refresh the page
7. The page shows properly

### Browsers affected

I tested on latest Chrome and Firefox and both are affected. Would expect Safari, IE and Edge to be as well.

**Comment by jbalsas** [comment]
Here's a library that might or might not help, just for reference: https://github.com/krux/postscribe

**Comment by eduardolundgren** [comment]
The expected behavior for `document.write` is to insert HTML into that dom position when the dom is in `loading` state, if dom is already `loaded` it clears all document to insert the new content. I am not sure whether or not we should fix that here in senna.

**Comment by jbalsas** [comment]
I opened this mostly because refreshing a page and navigating to it now renders different results.

This means at least that there's one case where you won't be able to simply add `senna.js` to your existing site and have it behave the same way.

**Comment by eduardolundgren** [comment]
Yes, this case is when Senna won't work is when `document.write` is being used. Is that possible to use this https://github.com/krux/postscribe as a polyfil that the user can plug on their side? Senna navigation  lifecycle could enable and disable the polyfil.

**Comment by jbalsas** [comment]
I did a quick test and couldn't get it to work, but I think we can do a more thorough research later to verify if this would be doable.

**Comment by fernandosouza** [comment]
Hey @jbalsas, `postscribe` works. You can check it [here](http://demo.sennademo.wedeploy.io/).

**Comment by fernandosouza** [comment]
Basically, it extracts from a given script parts that should be written into the document, in the case of the example I've made an `iframe`, and then, it append it inside a given `element`.

```
postscribe('#add', '<script src="https://slashdot.org/slashdot-it.js" type="text/javascript"></script>');
```

**Comment by jbalsas** [comment]
Hey @fernandosouza, that's nice! I meant that I tried to integrate it inside `senna.js` and couldn't get it to work.

The biggest question would be, how should we integrate this?
- Write our own version of the algorithm and integrate it inside `senna.js`
- Use `postscribe` inside `senna.js`
- Provide `postscribe` it as some kind of external hook or plugin

**Comment by fernandosouza** [comment]
I see, @jbalsas. It isn't an easy decision in my opinion. Does `Senna` intend to behave exactly the same as a Browser does on loading a page synchronously? If it does, we probably want to have this feature. We could start by solving this use case at least writing only the necessary code to solve it. 

If `Senna` doesn't intend to behave like that we can have a note for the users in the documentation and indicate `postscribe` as the solution.

**Comment by jbalsas** [comment]
To me, since we say you can simply drop `Senna` to any existing page, then I'd expect exactly the same behaviour. I'd rather have this built-in the library, but I can see how it can grow too much, so I'm open for discussion.

In case we don't introduce it, we should at least have a clear tutorial explaining how to integrate with `Senna` lifecycle to make it work using `postscribe` or similar.

**Comment by eduardolundgren** [comment]
The need for post dom-loaded `document.write` is not very common use-case, some complex application may need it. Let's add a tutorial in the new Senna website, we can make very clear how to use it together with `postscribe` instead of adding it to the core of the library.

**Comment by jbalsas** [comment]
Hey @eduardolundgren, I took a closer look at https://issues.liferay.com/browse/LPS-68414 and I agree this is more edge case than I originally assumed.

The biggest offender here is an [old StumbleUpon badge](http://www.stumbleupon.com/hostedbadge.php?s=5). The [new one](https://www.stumbleupon.com/dt/badges/create) seems to suffer from this as well, but might be circumvented via configuration.

I originally raised this because we thought the Facebook share widget was also using this technique, but further inspection has shown it isn't.

@fernandosouza, could you create a tutorial for this so we can publish it on the site and close this issue?

**Comment by fernandosouza** [comment]
Yes, I can @jbalsas. :)

This problem also happens with Slashdot service. But as you guys said, and I also agree, it's not a common use case, so a tutorial is sounds sufficient.

**Comment by jbalsas** [comment]
Hey @fernandosouza, can you work with @blzaugg to write a small tutorial about this so we can close it?

**Comment by fernandosouza** [comment]
Sure, @jbalsas.

**Comment by blzaugg** [comment]
@fernandosouza, either send me a Google doc, or send a PR to the `liferay/sennajs.com` repo, on the `electric` branch. I'll review it while I finish the project site migration.

**Comment by jbalsas** [comment]
Discarding myself!
