### ISSUE TITLE
How to handle response after form submit.

### ISSUE THREAD

**Issue by GusBeare** [liferay/senna.js#193]
I know this is not the ideal place to post this but I can't find anything in the docs or examples and there are no forums.

I have built a simple demo  app using Nancy FX.

https://github.com/GusBeare/Nancy-Senna-SPA

It all works really nicely.  However, it seems that Senna can handle form submissions but I can't find any examples of how to do this.

From the docs:

**_"Everything starts when you create a <code>var app = new senna.App();</code>, this class will route anchor link elements as well as form submissions."_**

I would like to be able to handle a json response after form submission from the server.  Can anyone show me how I might do this?

**Comment by eduardolundgren** [comment]
Did you have a chance to look https://github.com/liferay/senna.js/tree/master/examples/form?

**Comment by GusBeare** [comment]
ah, no, didn't find it. Thanks I'll check it out.

**Comment by eduardolundgren** [comment]
@GusBeare this example is handling html responses, although can also fetch JSON instead, then use it to repaint a component setting its state. If you need a more advanced example how to use Senna inside a router library you can see how this is being done in https://github.com/metal/metal-router - this might be too low level for your case.

**Comment by GusBeare** [comment]
thanks, 

Yeah, these examples are using node.js which I don't know well. 
 But I'll install it and have a play so I can understand it better.

If I can't get it to work I'll just turn off senna for the form and use jQuery forms.

cheers
Gus

**Comment by eduardolundgren** [comment]
@GusBeare the node.js is just to handle the request properly it can be any server-side technology

**Comment by GusBeare** [comment]
thanks yes.  I can run the node.js version locally and it works fine and returns the data in the form as such:

    {"name":"Jane","email":"Doe"}

But I can't work out how the results `<div>`  is getting updated?

I see the node server code:

    app.post('/post', upload.array(), function(req, res, next) {
 	var content = '<div id="result1">';
	content += JSON.stringify(req.body, 5);
	content += '</div>';
	res.end(content);
    });

But how do I do that at the back end in Nancy and get senna to update the div?

I have this C# now in my Nancy handler: The code is hit when I submit the form but I get a page refresh and the message appears with none of the calling page content.

 Post["/contactUs"] = p =>
            {
                    const string msg = "Success!"; 
                    return Response.AsText(msg);
            };

Any ideas?

**Comment by GusBeare** [comment]
I have it half working.  Am I correct in assuming that Senna is matching the result div from the server response and swapping it out with what it finds on the page?

This works server side:

    var msg = "<div id=\"result1\">Form successfully submitted at: " + DateTime.Today.ToString("yy-mm-dd") + " </div>";
    return Response.AsText(msg);

When I have this client side:

    <div id="result1" data-senna-surface>
        Waiting for post result...
    </div>

But I am now having trouble with navigating between pages. It works if I load the page directly or hit F5. If I navigate to another page and then back again or I arrive from another page it seems to post the form but not reach the back end.

**Comment by eduardolundgren** [comment]
@GusBeare If you are using `HtmlScreen` with surfaces you added by the id it will match the elements annotated as surfaces by the id, e.g. `<div id="surfaceIdYouGive" data-senna-surface>new content</div>` when the response from a navigation or form submission is HTML string it will grab the new content and update the dom with that.

**Comment by GusBeare** [comment]
Thanks @eduardolundgren.  I have it mostly working.

However, I still have the issue that unless I go direct to the page with the form on it the post does not hit the back end. When I click one of the links to load the contactUs page from another page I have to refresh the page before the form submit will work.

The basic views are here:

https://github.com/GusBeare/Nancy-Senna-SPA/tree/master/Views

And the basic server handler is here:

https://github.com/GusBeare/Nancy-Senna-SPA/blob/master/IndexModule.cs

Can you suggest anything dumb I'm doing?  It all works great without the form stuff.

**Comment by brunobasto** [comment]
Hey @GusBeare,

I noticed the contactUs page is not a surface. Is that correct? https://github.com/GusBeare/Nancy-Senna-SPA/blob/master/Views/contactUs.cshtml#L18

**Comment by GusBeare** [comment]
@brunobasto I've tried making the body a surface but when I do that the form submits but the page is re-loaded and the response message displayed on an empty page.

I noticed in the console that I am getting this when I submit the form after loading the contact us page:

Screen [screen_1] beforeDeactivate
senna-debug.js:7328 Navigate to [/contactUs]
senna-debug.js:7259 Already at destination, refresh navigation
senna-debug.js:6365 Screen [screen_1] deactivate
senna-debug.js:7998 Screen [screen_1] add content to surface [header] [...]
senna-debug.js:7998 Screen [screen_1] add content to surface [content] [...]
senna-debug.js:7998 Screen [screen_1] add content to surface [result1] [...]
senna-debug.js:6427 Screen [screen_1] flip
senna-debug.js:6314 Screen [screen_1] activate
senna-debug.js:7395 Navigation done

Notice "already at destination".  So when I refresh the page the form submit correctly.

All I want to achieve is home page plus three other pages. Each one has different content. The contact Us page has a form that does and ajax submit with the response message displayed under the form. 

Perhaps someone could modify the node.js /form example to do this so I can have something to replicate in my environment?

**Comment by GusBeare** [comment]
I got this to work. But only when I put `data-senna-off` in the link for the contact Us page which defeats the object.  I've tried just about everything I can think of. Am leaving it for now.

**Comment by brunobasto** [comment]
Hey Gus, the reason you are getting the Already at destination message is
because you are submitting the form to the same URL as the ContactUs page.
What you can do is change the action of the form to be something like
action="/contactUsAction". And in the back-end, after you process the data
you can redirect the user either to "/contactUs" or to a "thank you" page.
Whatever you want. I don't know how Nancy works, but most languages have
APIs for redirecting the response. If it doesn't, you can set the Location
header on the response to the URL you want the user to be redirected to.

**Comment by GusBeare** [comment]
@brunobasto  thanks for the help.

Nancy is able to differentiate between, GET, POST, PUT, DELETE etc HTTP methods and match the appropriate route.  [See Defining Nancy Routes](https://github.com/NancyFx/Nancy/wiki/Defining-routes)

e.g. from  `IndexModule.cs`

     Get["/contactUs"] = parameters => View["contactUs"];
     Post["/contactUs"] = p =>{ 
                  var msg = "<div id=\"result1\">Form successfully submitted at: " + DateTime.Now + "      </div>";
                    return Response.AsText(msg);
     };

With the above, a form post will hit the Post route and a Get will hit the Get. So it doesn't matter if they are given the same name. Nonetheless, I have changed it to be sure.  

In my post route Nancy sends back a string in the response which is what Senna should replace the matching DIV with as per the example form node.js app. (examples/form).

The version I have on Github now is not using senna to load the contact Us page but it is using Senna to do an Ajax Form post and update the results DIV on the page.  This is the best I've been able to manage for the scenario I was hoping for. It works but the Contact Us page is loaded with a full page load.

For now, I give up.

**Comment by brunobasto** [comment]
Hey Gus,

> With the above, a form post will hit the Post route and a Get will hit the Get. So it doesn't matter if they are given the same name. Nonetheless, I have changed it to be sure.

It matters for senna. It won't even make to request to the back-end because as far as senna knows, the screen you are navigating to is already cached.

If you could do something like:

`<form action="/contactUsAction"> ... </form>`

and on the backend you do:

`Response.Headers["Location"] = "/contactUs";`

Senna should make a request to '/contactUsAction' and then, once the back-end responds with the `Location` header set, the browser will follow the redirect to '/contactUs'. Senna will detect that a redirect was done, and will render the correct page accordingly.

**Comment by brunobasto** [comment]
@GusBeare,

Something like this, should do the trick to do the redirecting: https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Responses/RedirectResponse.cs#L18

**Comment by GusBeare** [comment]
@brunobasto many thanks for sticking with me. That fixed it!

   return Response.AsText(msg).WithHeader("Location", "/contactUs");

**Comment by brunobasto** [comment]
You are welcome!
