### ISSUE TITLE
Why does the build folder is not ignored by Git

### ISSUE THREAD

**Issue by fernandosouza** [liferay/senna.js#194]
If the only reason is to let applications load `Senna` from this folder, I think including the `postinstall` npm script can support this feature and we can start ignoring the folder. The `postinstall` script is run automatically after each `npm install` 

https://docs.npmjs.com/misc/scripts#examples

**Comment by zenorocha** [comment]
That was because of Bower :/

**Comment by brunobasto** [comment]
@fernandosouza, I'm closing this one since we still support it and we don't have plans to drop support for it yet.
