### ISSUE TITLE
POST request from form submission missing certain input types

### ISSUE THREAD

**Issue by SpencerWoo** [liferay/senna.js#199]
### Expected behaviour

There are various types, but specifically _input type="submit"_ should pass its name/values when it is triggering the post action as per https://www.w3.org/TR/html401/interact/forms.html#successful-controls.

### Actual behaviour

When submitting the form with the _input type="submit"_, the request does not have the input's values.

### Steps to reproduce

We'll modify an existing working example to reproduce issue.

1. Go to examples/forms/index.html
2. In the first form (action="/post") add _inputs_ of various types.  One of them being submit (_input type="submit" name="s" value="s"_).
3. Visit the webpage and submit the form via our input type="submit" (clicking the s button).
4. Verify no "s":"s" in result on page.  Verify input type="text" / "hidden" / etc sends properly.
5. Additionally look at the POST request sent via developer tools to verify.

### Browsers affected

I tested on Chrome, but I don't think its browser or multipart/form-data specific.

**Comment by fernandosouza** [comment]
Hey, @SpencerWoo. Thx for reporting. We are going to take a look it. :)

**Comment by brunobasto** [comment]
Hey @SpencerWoo, we are using HTML5 [FormData](https://xhr.spec.whatwg.org/#interface-formdata) to create the body of the request. I haven't tested it yet, but what you you describe suggests Chrome doesn't put the value of a submit button into the FormData. Gladly, the API allows us to add more values by calling `FormData.append()`.

Thx for reporting this.

**Comment by brunobasto** [comment]
For Reference: https://github.com/liferay/senna.js/blob/master/src/screen/RequestScreen.js#L208

**Comment by SpencerWoo** [comment]
Thanks all for looking at this.  As a note, I believe with a standard form (or when the form has "data-senna-off") the post request does contain the clicked submit button values.  

Thanks again for all the responses!

**Comment by SpencerWoo** [comment]
Hi all,

Any updates on this issue?

**Comment by brunobasto** [comment]
Hey @SpencerWoo, tackle this issue next. I'll let you know how it goes. Thx

**Comment by brunobasto** [comment]
@SpencerWoo, here's an initial draft: https://github.com/liferay/senna.js/pull/202

**Comment by brunobasto** [comment]
From the spec, I'm not sure if other kinds of buttons should go into the form data as well. Do you have any pointers on how the spec defines this behavior?

**Comment by brunobasto** [comment]
Ok, so I think my PR is not accurate. The spec says:

> If a form contains more than one submit button, only the activated submit button is successful.

So, I'll need to update my code.

**Comment by SpencerWoo** [comment]
Awesome thanks @brunobasto -- yeah as mentioned about the submit button, but from what I can tell everything else works properly (sends data as it does without senna.js).  This LPS (https://issues.liferay.com/browse/LPS-69556) mentions button, but I haven't verified.

**Comment by brunobasto** [comment]
Another piece of reference here: https://html.spec.whatwg.org/multipage/forms.html#constructing-the-form-data-set

> If any of the following conditions are met, then **skip** these substeps for this element:
>...
> The field element is disabled.
> The field element is a button but it is not submitter.

**Comment by brunobasto** [comment]
@SpencerWoo, do you happen to know what would be the expected behavior if an user submits the form using the enter key on a field inside the form? Would the value of the submit button go to the server as well? If there are more than one submit button, which one should go to the server?

**Comment by SpencerWoo** [comment]
@brunobasto I found this link (http://stackoverflow.com/questions/925334/how-is-the-default-submit-button-on-an-html-form-determined) which is basically saying there's no defined spec for submitting a form with the enter key and the browser chooses which submit button is the default (the triggering one).  On chrome it appears to be the first submit button.

**Comment by SpencerWoo** [comment]
From what I have tested that commit looks good!  Currently watching https://github.com/liferay/senna.js/pull/203.

**Comment by jbalsas** [comment]
Hey @SpencerWoo, @brunobasto, I think this is actually properly explained in the [Forms HTML5 Spec](https://www.w3.org/TR/html5/forms.html#forms), specially in the [Implicit submission](https://www.w3.org/TR/html5/forms.html#implicit-submission) section.

> A form element's default button is the first submit button in tree order whose form owner is that form element.
>
> If the user agent supports letting the user submit a form implicitly (for example, on some platforms hitting the "enter" key while a text field is focused implicitly submits the form), then doing so for a form whose default button has a defined activation behavior must cause the user agent to run synthetic click activation steps on that default button.

**Comment by brunobasto** [comment]
Awesome, then my fix proposal already accounts for that.

**Comment by ducthai93** [comment]
**Nothing**### [my](url)
