### ISSUE TITLE
Anchor links are dropped

### ISSUE THREAD

**Issue by caneta** [liferay/senna.js#207]
### Expected behaviour
On my local Liferay 7 DXP installation, I've created a web content with the following link
```
<a href="http://localhost:8080/en/web/my_site/my_other_page#my_anchor">
   my_other_page#my_anchor
</a>
```
I expected that clicking on this link, it would lead me to my_other_page#my_anchor

### Actual behaviour
Instead I land to my_other_page: the anchor is dropped.

### Steps to reproduce
[Liferay Forum Thread about this issue with steps](https://web.liferay.com/it/community/forums/-/message_boards/message/88341749)

### Browsers affected
Tested on latest version of Chrome

**Comment by brunobasto** [comment]
Hey @caneta, this has already been fixed in the previous release of senna : https://github.com/liferay/senna.js/releases/tag/v2.1.4

**Comment by caneta** [comment]
Thank you @brunobasto!
Upgrading my Liferay 7 DXP to Fix Pack 13, which includes senna.js 2.1.4 ([LPS-71199](https://issues.liferay.com/browse/LPS-71199)), solved the issue.
