### ISSUE TITLE
Senna doesn't respect link target attribute

### ISSUE THREAD

**Issue by brunobasto** [liferay/senna.js#211]
### Expected behaviour

When clicking on a link with target="_blank", it's expected that the link will open on a new tab.

### Actual behavior

Senna ignores the attribute and navigates to the link on the same tab.

### Steps to reproduce

1. Add a link where the href attribute is routed by senna.
1. Add a target="_blank" to that link.
2. Click on that link

### Browsers affected

All major browsers.

**Comment by zenorocha** [comment]
+1, we had this bug this morning, had to add `data-senna-off` to workaround.

**Comment by brunobasto** [comment]
@fernandosouza,  can you are a looks at this when you have some time? It's should be enough to change this line https://github.com/liferay/senna.js/blob/master/src/app/App.js#L101 to not track links with the target attribute set.

**Comment by fernandosouza** [comment]
Sure, @brunobasto. I'm going to take a look.

**Comment by brunobasto** [comment]
Hey @fernandosouza, what's the status on this one?

**Comment by eduardolundgren** [comment]
LGTM

**Comment by fernandosouza** [comment]
Hey, @brunobasto. I'll check if I missed anything and I'm going to send a PR.
