### ISSUE TITLE
Flaky Test 'App should wait for pendingNavigate before removing screen on double back navigation'

### ISSUE THREAD

**Issue by jbalsas** [liferay/senna.js#216]
There's currently a flaky test in the senna suite:

```
Mobile Safari 9.0.0 (iOS 9.2.0) App should wait for pendingNavigate before removing screen on double back navigation FAILED
	timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

See this [Travis Report](https://travis-ci.org/liferay/senna.js/builds/235203989#L3316)

**Comment by brunobasto** [comment]
@fernandosouza, this is the test with the setTimeout for handling the Safari debounced history.back. Can you double check? 

Thx

**Comment by fernandosouza** [comment]
Yeah, @brunobasto. That is it.

**Comment by jbalsas** [comment]
Hey @fernandosouza, any update on this?

**Comment by jbalsas** [comment]
I don't think this is flaky anymore 😂
