### ISSUE TITLE
Anchor link offset are not calculated correctly

### ISSUE THREAD

**Issue by dacousalr** [liferay/senna.js#221]
### Expected behaviour

Clicking in anchor links under a Liferay environment should set the scroll to the correponding element.

### Actual behaviour

Clicking in anchor links under a Liferay environment set the scroll without calculating the offset of the ancestor elements.

### Steps to reproduce

To test this in a Liferay enviroment [LPS-43629](https://issues.liferay.com/browse/LPS-43629) should be reverted and follow the reproduction steps of [LPS-71809](https://issues.liferay.com/browse/LPS-71809).

### Possible solution

https://github.com/liferay/senna.js/pull/220

**Comment by brunobasto** [comment]
Hey @dacousalr, I've sent you a pull request updating senna.js in portal to the version containing the fix: https://github.com/dacousalr/liferay-portal/pull/9

Thx

**Comment by dacousalr** [comment]
Thank you so much, @brunobasto

**Comment by caneta** [comment]
Hi all, same problem here working with a Liferay 7 DXP fixpack-25.
In which way should I fix this issue in a production environment? Any suggestions?

**Comment by brunobasto** [comment]
Fixed by https://github.com/liferay/senna.js/pull/220

**Comment by brunobasto** [comment]
@caneta, you should have it fixed if you apply [this fixpack](https://issues.liferay.com/browse/LPS-61883?jql=labels%20%3D%20liferay-fixpack-portal-85-6210)

**Comment by caneta** [comment]
Thank you @brunobasto: in the link there is a fixpack for Liferay 6.2 but I need it for a Liferay 7 DXP. Is it available yet?

**Comment by dacousalr** [comment]
Hi @caneta, the solution for Liferay 7 DXP is not available yet but it will be soon.

**Comment by caneta** [comment]
I see that fixpack de-29 for Liferay 7 DXP is out, but I cannot find in its [releases notes](https://issues.liferay.com/issues/?jql=labels%20%3D%20liferay-fixpack-de-29-7010&_ga=2.66092524.319413082.1503922734-199699759.1448900023) if it solves this issue.
The Liferay Issue ID should be [LPS-71809](https://issues.liferay.com/browse/LPS-71809?_ga=2.75389776.319413082.1503922734-199699759.1448900023).
Any idea on when it will be available on a regular fixpack?
Thank you

**Comment by alfonsocrisci** [comment]
The fix has been released in the "de-30-7010" DXP fix pack.
