### ISSUE TITLE
Broken Favicon with IE11

### ISSUE THREAD

**Issue by SpencerWoo** [liferay/senna.js#228]
### Expected behaviour

The favicon in the browser tab uses the senna.js favicon instead of the IE default favicon.

### Actual behaviour

The favicon in the browser tab uses the IE default favicon until refresh.

### Steps to reproduce

1. Start senna.js server and open the turbolinks example (localhost:8888/examples/turbolinks/) in IE 11.
2. Clear browser cache.
3. Click "Index" hyperlink (turbolink).  Notice the IE tab icon.
4. Refresh.  Notice it changed to senna tab icon.
5. Repeat on other pages.

### Browsers affected

I tested on all major browsers and only IE 11 does not work.

**Comment by brunobasto** [comment]
Hey @SpencerWoo, I'm still looking into it and haven't got to any conclusions yet, but I did find it to be a [known issue](https://connect.microsoft.com/IE/feedback/details/1008701/when-doing-a-history-pushstate-internet-explorer-doesnt-account-for-the-base-tag-for-the-favicon) that Microsoft closed as won't fix. Also see: https://connect.microsoft.com/IE/feedback/details/1443745/favicon-disappears-when-history-pushstate-is-called

To this date, it seem it also affects youtube.com and I found that SPA React apps seem to also suffer from it: https://medium.com/@cameronbourke/a-tale-of-favicons-and-react-dbcb4e7202e4

**Comment by brunobasto** [comment]
I'm closing this as I don't think there's much we can do on the framework level.
