### ISSUE TITLE
Examples are 404

### ISSUE THREAD

**Issue by nicolas-raoul** [liferay/senna.js#231]
https://github.com/liferay/senna.js#examples
These examples are also featured prominently at https://sennajs.com

https://sennajs.com/examples/static.html is 404
The other don't work much better.

It would be great to have working examples to see. Thanks!

**Comment by brunobasto** [comment]
Hey @zenorocha, can you check sennajs.com to see what's going on?

**Comment by jbalsas** [comment]
Examples seem to be up:
- https://sennajs.com/examples/email/
- https://sennajs.com/examples/gallery/static.html
- https://sennajs.com/examples/blog/
