### ISSUE TITLE
TODO: Remove workaround to prevent DOM Exception 18 during unit tests execution on Safari

### ISSUE THREAD

**Issue by brunobasto** [liferay/senna.js#247]
Right now we have a [workaround](https://github.com/liferay/senna.js/pull/246/commits/303397bd24a06c3d7e3d1234fd7f99cfaee408e1) on our unit tests to prevent DOM Exception 18 on Safari. More informations about why they introduced this limitation [here](https://bugs.webkit.org/show_bug.cgi?id=156115). With that workaround, the tests on travis became stable again.

The solution is pretty ugly, as it relies on a synchronous timeout, which requires heavy processing. It's important to notice that it's **only for the unit tests** we do **NOT** execute this kind of thing on our released code.

**Comment by jbalsas** [comment]
Looks like the workaround is there to stay :D
