### ISSUE TITLE
Customize loading bar color in Liferay DXP fixpack 36

### ISSUE THREAD

**Issue by caneta** [liferay/senna.js#249]
I would like to customize background color of senna loading bar inside a Liferay DXP fixpack 36 portal.

Looking at it's [css here](https://github.com/liferay/senna.js/blob/master/src/senna.css), I guessed to get it setting inside my custom theme main.css file the following:
```
.senna-loading-bar {
  background: red;
}
```
But this does not work...I cannot even find the senna.css file loaded inside my pages, searching for it with developer tools...

How to get it work?

Thank you

**Comment by diegonvs** [comment]
Hey @caneta , probably you are overwriting incorrect class.
![screen shot 2018-01-24 at 14 07 02](https://user-images.githubusercontent.com/7663513/35346021-e207e036-010f-11e8-9933-997fef7e5706.png)
Did you try use `Liferay.spa.app.setLoadingCssClass()`?

**Comment by diegonvs** [comment]
Can you try to overwrite this css class in the theme?

![screen shot 2018-01-24 at 14 58 19](https://user-images.githubusercontent.com/7663513/35348562-279970b8-0117-11e8-96c8-bd80c537ffd3.png)

**Comment by caneta** [comment]
Overwriting that class did the trick,  thank you @diegonvs!
I've written the following inside my _my-theme/src/css/)custom.scss_:
```
.lfr-spa-loading-bar {
  background: red;
}
```
