### ISSUE TITLE
Accesibility error on iframe

### ISSUE THREAD

**Issue by salvatejero** [liferay/senna.js#250]
### Expected behaviour

Pass accessibility plan successfully

### Actual behaviour

Not pass.

### Browsers affected

Koa11y App finds a accesibility problem with Senna.js

Koa11y App finds a accesibility problem with Senna.js

During the page load, a iframe appears.

Please, add a title attribute to this iframe.

senna.js/build/globals/senna.js Line 779.

Regards

**Comment by matuzalemsteles** [comment]
hey @salvatejero, Thanks for the report!

Just to inform you, senna.js uses the `metal` package and the `async.nextTick` utility to implement the iframe in some use cases like yours.

**Comment by jbalsas** [comment]
I guess this was fixed since the fix was merged looong time ago. Not sure if it made it all the way to all the target platforms.

@salvatejero, please feel free to reopen if you're still seeing this!
