### ISSUE TITLE
Different ports are considered same origin

### ISSUE THREAD

**Issue by jbalsas** [liferay/senna.js#254]
### Expected behaviour

I expected that, from a `localhost:8080/foo` location, clicking on a link for `localhost:9080/bar` (different port) would be detected as an external navigation and cause a full refresh

### Actual behaviour

Instead of refreshing the page and navigating to the full url, the basepath and port are kept and senna tries to navigate via ajax to `localhost:8080/bar` (wrong port).

### Steps to reproduce

This should be more or less straightforward by looking at [App.js::canNavigate](https://github.com/liferay/senna.js/blob/master/src/app/App.js#L289-L316)

It has been filed as an [issue in Liferay Portal](https://issues.liferay.com/browse/LPS-78230)

### Browsers affected

All browsers

/cc @eduardolundgren, any reason to not check for port?

**Comment by jbalsas** [comment]
Hey @diegonvs, go for it!

If you could take a look at https://github.com/liferay/senna.js/pull/251 too it would be really helpful!

**Comment by jbalsas** [comment]
We might just need to use `location.host` rather than `location.hostname`

**Comment by diegonvs** [comment]
#256
