### ISSUE TITLE
Remove the console.log when publishing

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/senna.js#272]
### Expected behaviour

No logs should appear in the console when you are using senna in production.

### Actual behaviour

Currently there are logs appearing on the console when you are using senna.

### Steps to reproduce

Use Senna as a dependency and navigate anywhere with it.

**Comment by jbalsas** [comment]
Hey @matuzalemsteles, I think this is twofold... on one side, we should be generating the proper distribution files, but afaict, we're also using straight from sources in Liferay Portal, so we should do something slightly different there, shouldn't we?

**Comment by matuzalemsteles** [comment]
hey @jbalsas, In Liferay Portal 7.0.x, we build the senna with gradle, collecting the `node_modules/senna/build/amd/senna/` files would be more complicated to do there, but in 7.1 we use `liferay-npm-bundler` to get the dependencies, so it picks up from `lib`.

I put some comments in the PR.

**Comment by jbalsas** [comment]
👍
