### ISSUE TITLE
Turn Cache on Screens off

### ISSUE THREAD

**Issue by Aurugorn** [liferay/senna.js#287]
Is there an easy way to turn cache off on screens? My pages are based on database values. So my pages need to be up to date all the time. Now it reads the cached page which is the old version.
Not sure if there is another way to do this. Can't find anything on Google.
Thanks in advance!
PS. LOVE Senna so far! Awesome script!

**Comment by diegonvs** [comment]
Hello Stan! Thanks for collaborating filling this issue :)

How are you using `senna` App? You are extending `senna` App?

**Comment by Aurugorn** [comment]
Thanks for the quick response!
Currently using it with turbolinks. Just adding senna-surface etc. as tags. It is working perfectly! But my pages must be up to date always (for example I have a page with a schedule that can be updated any time). 
Thanks in advance for helping!

**Comment by lneves12** [comment]
Hi @Aurugorn, 

I had the same problem as you. 
You can have a bit more control of your cache like this: 

```javascript
import App, {HtmlScreen} from "senna";

var appInstance = new App();
appInstance.setLinkSelector("a.js-spa");
appInstance.setFormSelector("");
appInstance.addSurfaces('page-body');
appInstance.addRoutes([{
    path: /.*/,
    handler: function (route) {
        const screen = new HtmlScreen();
        screen.setCacheable(false);
        return screen;
    }
}]);

```

**Comment by jbalsas** [comment]
Closing based on the provided workaround. Please, feel free to reopen if still need something else!
