### ISSUE TITLE
Improve Blog responsive sidebar usability

### ISSUE THREAD

**Issue by bernarddeluna** [liferay/senna.js#29]
when you are using mobile screen, you need a easy-access to nav and header, in another words, it will be nice to put a hamburger icon and slide the sidebar above your content:

something like this: https://dribbble.com/shots/1325069-IOS-7-Sidebar-Menu?list=searches&offset=22

**Comment by eduardolundgren** [comment]
Examples being re-organized. Thanks @bernarddeluna.
