### ISSUE TITLE
Senna.js not working when navigating between pages when using a Web Server + SSL on IE11

### ISSUE THREAD

**Issue by gregory-bretall** [liferay/senna.js#290]
### Expected behaviour

Senna.js works as expected when using a web server + SSL on IE11

### Actual behaviour

Senna.js does not work

### Steps to reproduce

1. Download the SSL Web Server vm here: https://ftp.liferay.com/LBv2.zip 
2. Extract and open the vm, edit the following file to use your host machine IP:
C:\Apache24\conf\liferay\liferay-ssl-lb.conf
```
<Proxy balancer://sslcluster/>
	BalancerMember https://172.16.21.206:8443
</Proxy>
```
3. Restart/start Apache by going to the bottom right Apache icon>restart 
4. Setup Liferay on your host machine: configure Tomcat server to use HTTPS (https://customer.liferay.com/documentation/knowledge-base/-/kb/14494)
5. Startup Liferay and access it through https://[webserver_IP] on IE 11 (I tested in Windows 10, not sure if that matters)
6. Create site pages with some content
7. Click around to load new pages/content that causes the yellow bar to appear
9. The yellow bar does not appear

### Browsers affected

I tested on all major browsers and only IE 11 does not work.

This issue is also tracked on the Liferay side on https://issues.liferay.com/browse/LPS-87416.

**Comment by gregory-bretall** [comment]
PR for this issue is found here https://github.com/liferay/senna.js/pull/291

**Comment by diegonvs** [comment]
Closing this one, since the fix was already merged. Any question, please, reopen it :)
