### ISSUE TITLE
Page keyword metatag is not being refreshed after page navigation

### ISSUE THREAD

**Issue by marcellustavares** [liferay/senna.js#298]
### Expected behaviour

After SPA page navigation, the keyword meta tag gets updated.

### Actual behaviour

The keywords meta tag gets refreshed after a hard page refresh.

**Comment by brunobasto** [comment]
@diegonvs

**Comment by marcellustavares** [comment]
Thanks a lot @diegonvs! can you let me know whenever we get this fixed released?
