### ISSUE TITLE
Use feature detection to disable senna when used in a unsupported browser environment

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [liferay/senna.js#60]
Senna should use a feature detection system to disable itself for unsupported browsers, that could be a useful feature in the meantime because it would allow the app to work without the need to worry about how older browsers are behaving when using the framework.

x-ref: https://github.com/eduardolundgren/senna/issues/34#issuecomment-55365998

**Comment by eduardolundgren** [comment]
Done on branch v1.0.0-alpha.
