### ISSUE TITLE
Who uses Senna?

### ISSUE THREAD

**Issue by eduardolundgren** [liferay/senna.js#63]
Let us know if your project/company uses Senna and wouldn't mind being mentioned on the website. Include a logo with a link to the project if you have one.

**Comment by lpgray** [comment]
[Students Helper(同学帮帮)](http://txbb.com/m) is using senna now.

![http://txbb.com/mpub/dist/img/com/icon_240.png](http://txbb.com/mpub/dist/img/com/icon_240.png)

**Comment by sachinhub** [comment]
Hi, I have a question. We are running a site using Liferay 6.1 and wanted to know if we can use sennajs with that. 

We want to intercept all page navigations and make them as ajax calls and update DOM and was thinking if we can use sennajs in any way with LR6.1

**Comment by jbalsas** [comment]
Thanks for everyone that has used and continues using Senna!

Triaging to see which issues merit action to have a clear picture of what we still want to do in the context of the project.
