### ISSUE TITLE
Cache invalidation

### ISSUE THREAD

**Issue by henvic** [liferay/senna.js#68]
Yesterday @marcellustavares told me about a issue which I describe bellow with an example.

Given the mapping `/posts/<post-id>`,

1. navigate to /posts/100
2. navigate to /posts/batch-editing and edit the blog title for the post with `id = 100` to something else
3. navigate to any other place without a full page refresh
4. navigate again to /posts/100

You're going to see the old version of /posts/100.

Some options to solve this:
* Create a cache invalidation method that once called should invalidate all the routes that match the given pattern.
* Create an option to always verify the content freshness with ETag headers. With this option, if the content wasn't updated the request would basically be like a HEAD request, otherwise the content would be sent to the client for updating. We've have to decide if it's more appropriate to show content and replacing it later in case of invalidation or block the UI while the verification is being made.

**Comment by eduardolundgren** [comment]
This should be enough for now https://github.com/liferay/senna.js/blob/master/src/app/App.js#L241. Thanks!
