### ISSUE TITLE
Script load error: 404 with relative URLs

### ISSUE THREAD

**Issue by danielfariati** [liferay/senna.js#85]
There is an error when loading scripts in different contexts with relative URL.

For example:
Let's say that we have the following pages:

*/context1/index.html* that have the following script import:
```<script src="js/script1.js"></script>```

*/context2/index.html* that have the following script import:
```<script src="js/script2.js"></script>```

When we change from the first page to the other one, an error is thrown:
*GET http://localhost:8888/context1/js/script2.js 404 (Not Found)*

My theory is that we're only changing the browser history after the scripts are parsed, so the browser does not recognize the relative URL.

**Comment by eduardolundgren** [comment]
That make sense. It's likely to be the root cause. I will try to work on a fix for that this week. Feel free to send a pull to that as well. Sorry for delaying.
