### ISSUE TITLE
The vertical height is not maintained after Surface flip

### ISSUE THREAD

**Issue by RobinNagpal** [liferay/senna.js#90]
I am using liferay 7, and I dropped 4-5 portlets on my page. On the flip of the surface of the bottom most portlet, my vertical scroll height is not maintained.

**Comment by RobinNagpal** [comment]
@eduardolundgren 

I see you added this function. Can you please share why is it required? The scroll position is already saved with state.

 senna.App.prototype.syncScrollPosition_ = function(opt_replaceHistory) {
    var scrollLeft = opt_replaceHistory ? this.syncScrollLeft : 0;
    var scrollTop = opt_replaceHistory ? this.syncScrollTop : 0;

    if (this.updateScrollPosition) {
      window.scrollTo(scrollLeft, scrollTop);
    }

    this.storeScrollPosition_(scrollLeft, scrollTop);
  };

**Comment by eduardolundgren** [comment]
The scroll is stored natively by history API, although when state changes the browser updates its position right away, potentially before the surfaces content are ready since the lifecycle is deferred. Therefore, we wait that the entire lifecycle is ready in order to re-position the scroll for better UX.

**Comment by RobinNagpal** [comment]
@eduardolundgren  agree! But this is currently not working using Senna.js i.e. scroll is not maintained or re-positioned. 

1) opt_replaceHistory in the above function is false for next surface.
2) we dont update  this.syncScrollLeft  or  this.syncScrollTo, everything these is change in the scroll position

**Comment by remisbaima** [comment]
+1
SennaJS worked amazingly for my use-case (i.e. pagination). But I have the same problem described in this issue.

**Comment by eduardolundgren** [comment]
Could you write a test case?

**Comment by RobinNagpal** [comment]
Sure, I can trying doing that and can also try sending you a pull request with the solution

**Comment by eduardolundgren** [comment]
This is already fixed on master and on v1.0.0-alpha. Thank you.
