### ISSUE TITLE
Safari/Windows: "endNavigate" event is not triggered in the test to remember the scroll position

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [liferay/senna.js#92]
The following code is not triggered when running the test suite in Safari 5.1.7 on Windows 7:

https://github.com/eduardolundgren/senna/blob/234dff5fd48ad75fc6a0eca8748dc907540a07e1/test/test.js#L472-L477

![image](https://cloud.githubusercontent.com/assets/835857/6797561/43efc26a-d1e2-11e4-8114-595b1b2b9308.png)

Since the assertions and the "done" function is never triggered the test timed out.

It turns out this code is not being executed in Safari: https://github.com/eduardolundgren/senna/blob/234dff5fd48ad75fc6a0eca8748dc907540a07e1/src/utils/EventEmitter.js#L95-L96

The same is happening here:
https://github.com/eduardolundgren/senna/blob/234dff5fd48ad75fc6a0eca8748dc907540a07e1/test/test.js#L503-L507

and here:
https://github.com/eduardolundgren/senna/blob/234dff5fd48ad75fc6a0eca8748dc907540a07e1/test/test.js#L601-L603

@eduardolundgren Any idea to help narrow down this problem? You have a much better knowledge of the internals (obviously :P).

**Comment by eduardolundgren** [comment]
I am swamped in a project this week. Anyways, I will try to create a milestone release to address all the issues you have filed. If you have any progress in between let me know.

**Comment by eduardolundgren** [comment]
Hey @FagnerMartinsBrack, some refactor were made on branch v1.0.0-alpha to prepare final release. This is no longer valid. Thank you for reporting.

**Comment by FagnerMartinsBrack** [comment]
:+1:
