### ISSUE TITLE
Safari/Windows: '[object MouseEventConstructor]' is not a constructor (evaluating 'new MouseEvent(type, modifiers)')

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [liferay/senna.js#93]
The mouse related test doesn't work in Safari 5.1.7 on Windows 7:

https://github.com/eduardolundgren/senna/blob/234dff5fd48ad75fc6a0eca8748dc907540a07e1/test/test.js#L575

It seems Safari doesn't support dispatching an event in a `MouseEvent` instance, it throws the error below:

![image](https://cloud.githubusercontent.com/assets/835857/6797832/7de7828e-d1e5-11e4-97b2-c080a1bd7138.png)

I did a fast research and couldn't find the root cause, need to check the spec.

**Comment by eduardolundgren** [comment]
Reorganized on v1.0.0-alpha.
