### ISSUE TITLE
Rename project due to copyright violations

### ISSUE THREAD

**Issue by zenorocha** [liferay/senna.js#95]
Even though this is an open source initiative and does not generate any profit, we'll have to change its name due to copyrights™. 

Any suggestions?

**Comment by zenorocha** [comment]
Here're some of the things we need to change:

- [ ] Site
    - [ ] Examples
- [ ] GitHub
    - [ ] Releases
- [ ] Bower
- [ ] npm

**Comment by zenorocha** [comment]
https://github.com/eduardolundgren/senna/commit/5ba8f2af7c8cd63979c968fc3f7928f10564ec31

**Comment by henvic** [comment]
Hyperloop http://www.teslamotors.com/blog/hyperloop

The reference is great. Elon Musk is awesome and is very welcome to open source.

Recently Tesla started moved their patents to an open-source model patents and SpaceX photos are now public domain thanks to him.

http://www.teslamotors.com/blog/all-our-patent-are-belong-you

**Comment by gawry** [comment]
Is that the reason the site and examples are offline?

**Comment by eduardolundgren** [comment]
Unfortunately, we had to remove the site domain. Senna name is a trademark in Brazil and they are very strict about using it. In couple of days it will be back online.

Sorry about the inconvenience.

**Comment by FagnerMartinsBrack** [comment]
Alright, Senna is a trademark, but is SennaJS a trademark also?

**Comment by tapmodo** [comment]
I came across this issue today when looking for API documentation, this is a real bummer! If you want to keep the fast/race car theme, my suggestion for a name is "pettyjs" for [Richard Petty](http://en.wikipedia.org/wiki/List_of_all-time_NASCAR_Cup_Series_winners)—no one can trademark "petty" (a common English word). Biggest problem right now is no online documentation or website totally missing...settling on a name will fix it? Let's go. I'll sponsor the domain name if you want (contact me)... thanks for the great project!

**Comment by zenorocha** [comment]
I found a solution: http://en.wikipedia.org/wiki/Senna_(plant)

**Comment by eduardolundgren** [comment]
Closing the issue since it's already solved. Thx.
