### ISSUE TITLE
How i can run router handler after first page load 

### ISSUE THREAD

**Issue by Claud** [liferay/senna.js#98]
Hello. I have a simple app:

```js
    var app = new senna.App();
    app.setLinkSelector('a:not([data-senna-off]), a:not([href="#"])');
    app.addSurfaces('senna-main-content');
    app.addRoutes([
        new senna.Route('page1.html', senna.Page1Screen),
        new senna.Route('page2.html', senna.Page2Screen),
    ]);
```
and different "screen" classes that has unique code in the activate method.

How i can run router handler after first page load (when the user visited the site.)?

**Comment by Claud** [comment]
I has wrote this solution.

```js
if (router) {
        let handler = router.getHandler();
        let instance = new handler();
        instance.activate();
    }
```
But if has more true solution, please write it.

**Comment by eduardolundgren** [comment]
Sorry, the problem wasn't clear. Could you explain with more details what you are trying?

**Comment by davidguilherme** [comment]
Imagine this situation: A simple app where the App Server render index.html to all requests. So, the senna app will resolve the path. And, the all pages will just partials (containing only senna surface).

So, a simple `app.dispatch();` in the end will resolve.
