### ISSUE TITLE
<link rel="senna-route"...> not work for me

### ISSUE THREAD

**Issue by Claud** [liferay/senna.js#99]
Hello. `<link rel="senna-route" href="regex:.*" type="HtmlScreen">` it is not work for me. What am i doing wrong?
```
Senna initialized from data attribute.
bundle.min.js:1600 Uncaught Error: Route handler is not a function.
```

**Comment by eduardolundgren** [comment]
Try `<link rel="senna-route" href="regex:.*" type="senna.HtmlScreen">`.

**Comment by Claud** [comment]
@eduardolundgren thanks you it is work.

**Comment by Claud** [comment]
@eduardolundgren It is solution has error.

```js
var app = new senna.App();
var route = app.findRoute(window.location.href); // retrun null
```
`app.routes` is empty.

**Comment by Claud** [comment]
Simple solution 

```js
$('link[rel="senna-route"]', 'head').each(function(key, item) {
    var handler = senna[$(item).attr('type')];
    var path = $(item).attr('href');
    var index = path.indexOf('regex:');
    if (index > -1) {
        path = new RegExp(path.substr(6));
    }
    app.addRoutes(new senna.Route(path, handler));
});
```

**Comment by eduardolundgren** [comment]
When you use data attributes you need to use the shared senna app intance:

`var app = senna.dataAttributeHandler.getApp();`

This will work.

**Comment by Claud** [comment]
Uncaught TypeError: Cannot read property 'getApp' of undefined

**Comment by eduardolundgren** [comment]
Did you put data-senna attribute on the body?

**Comment by Claud** [comment]
Yes of course 

```
<body class="senna-transition-fade" data-senna>
    <div class="senna-loading-bar"></div>
```

**Comment by eduardolundgren** [comment]
I assume you are calling that before DOM is ready and the data attribute handler starts on dom content load.

Could you do another try?

```
document.addEventListener('DOMContentLoaded', function() {
   var app = senna.dataAttributeHandler.getApp();
});
```

**Comment by Claud** [comment]
I thought about it. And it did not help.

**Comment by eduardolundgren** [comment]
You need to make sure you are binding DOMContentLoaded (or jQuery.ready) after senna.js is included in the page in order to be fired after the internal listener.

If it does not work, please, send some example because here it works fine.
